language: rust
rust:
  - 1.28.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - FEATURES=""
  - FEATURES="rayon"
script:
  - cargo build --verbose --no-default-features --features "$FEATURES"
  - cargo test --verbose --no-default-features --features "$FEATURES"
